// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using synonymsAPI.Database;

namespace synonymsAPI.Migrations
{
    [DbContext(typeof(synonymsDbContext))]
    partial class synonymsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.13")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("synonymsAPI.Database.wordConnections", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("word1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("word2")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("wordConnections");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            word1 = "hurry",
                            word2 = "run"
                        },
                        new
                        {
                            Id = 2,
                            word1 = "hurry",
                            word2 = "rush"
                        },
                        new
                        {
                            Id = 3,
                            word1 = "run",
                            word2 = "hurry"
                        },
                        new
                        {
                            Id = 4,
                            word1 = "rush",
                            word2 = "hurry"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
